/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import algorithm.Recommender;
import javax.swing.*;
import java.util.List;
/**
 *
 * @author macbookpro
 */
public class TargetUserPanel extends javax.swing.JPanel {
    private Recommender recommender;
    /**
     * Creates new form TargetUserPanel
     */
    public TargetUserPanel(Recommender recommender) {

      this.recommender = recommender;

      initComponents();
      applyTheme();

      loadUsers();

      recommendButton.addActionListener(e -> getRecommendations());
    }
    
    private void applyTheme() {

    UIStyle.stylePanel(this);

    UIStyle.styleButton(recommendButton);

    UIStyle.styleComboBox(userComboBox);

    UIStyle.styleTextField(xField);
    UIStyle.styleTextField(kField);

    UIStyle.styleTextArea(resultArea);
   }
    
    private void loadUsers() {

     List<Integer> users = recommender.getTargetUserIds();

     userComboBox.removeAllItems();

     for (Integer id : users) {
         userComboBox.addItem(String.valueOf(id));
        }
    }
    
    private void getRecommendations() {

    try {

        int userId = Integer.parseInt(userComboBox.getSelectedItem().toString());

        float[] targetVector =
                recommender.getTargetUserVector(userId);

        int x =
                Integer.parseInt(xField.getText());

        int k =
                Integer.parseInt(kField.getText());

        List<String> recommendations =
                recommender.getRecommendations(
                        targetVector,
                        x,
                        k
                );

        resultArea.setText("");

        for (String movie : recommendations) {

            resultArea.append(movie + "\n");
        }

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + ex.getMessage()
        );
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TargetUser = new javax.swing.JLabel();
        userComboBox = new javax.swing.JComboBox<>();
        X = new javax.swing.JLabel();
        xField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kField = new javax.swing.JTextField();
        recommendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();

        setSize(new java.awt.Dimension(900, 600));

        TargetUser.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        TargetUser.setText("Target User");

        userComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        userComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        X.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        X.setText("X:");

        xField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        xField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("K:");

        kField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        recommendButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        recommendButton.setText("Recommend");

        resultArea.setColumns(20);
        resultArea.setLineWrap(true);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TargetUser)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userComboBox, 0, 175, Short.MAX_VALUE)
                                    .addComponent(xField)
                                    .addComponent(kField)))
                            .addComponent(recommendButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TargetUser)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(recommendButton)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TargetUser;
    private javax.swing.JLabel X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kField;
    private javax.swing.JButton recommendButton;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JComboBox<String> userComboBox;
    private javax.swing.JTextField xField;
    // End of variables declaration//GEN-END:variables
}
